### ISSUE TITLE
is this issue from a mistake i made or what ?

### ISSUE THREAD

**Issue by MedoGamer888** [InoriRus/Kyty#11]
exe_name = E:/Kyty/Kyty/Kyty/fc_script.exe
Initialized: Config
Initialized: Profiler
Initialized: Log
Initialized: Timer
Initialized: Pthread
Initialized: Network
Initialized: Memory
Initialized: FileSystem
Initialized: Controller
Initialized: Graphics
Initialized: Audio
--- Stack Trace ---
[0] 0000000140274492, 0000000140274310, RuntimeLinker.cpp.obj, Kyty::Loader::RelocateHandler(Kyty::Loader::RelocateHandlerStack)
[1] 0000000010122bb9, 0000000000000000, unknown, unknown
[2] 0000000000000050, 0000000000000000, unknown, unknown
[3] 0000000010122bb9, 0000000000000000, unknown, unknown
[4] 0000000140599f08, 0000000000000000, unknown, unknown
--- Error ---
=== Unpatched function!!! ===
[9]     bzQExy189ZI[libc_v1][libc_v1.1][Func]
 in C:/projects/kyty/source/emulator/src/RuntimeLinker.cpp:459

**Comment by MasonLeeBack** [comment]
The libc function (in this case, printf according to the hash) is not implemented on the emulator as of yet.

**Comment by MedoGamer888** [comment]
> The libc function (in this case, printf according to the hash) is not implemented on the emulator as of yet.

actually i managed to get past that error now i get another error 
Exception!!! in C:/projects/kyty/source/lib/Core/src/Debug.cpp:85

**Comment by gandalfthewhite19890404** [comment]
It is init_env, not printf. 
Or I just mistook.

**Comment by MasonLeeBack** [comment]
> It is init_env, not printf. Or I just mistook.

You could be correct, I didn't do too much digging other than compiling a test app for the program.

**Comment by Brutal-sam** [comment]
![Capture](https://user-images.githubusercontent.com/94696121/170566633-51983ec0-bdf4-4dbc-9e3e-df8cc905615a.JPG)
what does this kernel error mean

**Comment by InoriRus** [comment]
It means that function **DGMG3JshrZU** (sceKernelSetVirtualRangeName) is not implemented

DGMG3JshrZU is hash of function signature
You can find real name here:
https://github.com/idc/ps4libdoc/blob/8d0ffa6091d2da9268bd84aaaf372c76b5bf062d/system/common/lib/libkernel.sprx.json#L4449
