### ISSUE TITLE
multiple issues with initial commit code

### ISSUE THREAD

**Issue by zecoxao** [InoriRus/Kyty#2]
1. Kyty/source/3rdparty/easy_profiler/src/event_trace_win.cpp:237:19: error: 'GetProcessIdOfThrea
' was not declared in this scope
  237 |             pid = GetProcessIdOfThread(hThread);
  
  solved by 
  #define _WIN32_WINNT  0x0600
  
  at top of cpp
  
  2. Kyty/source/emulator/src/Graphics/Tile.cpp:434:20: error: comparison of integer expressions of different signedness: 'int' and 'uint32_t' {aka 'unsigned int'} [-Werror=sign-compare]
  434 |  for (int l = 0; l < levels; l++)
  
  solved by
  
  for (uint32_t l = 0; l < levels; l++)
  
  3. error at linking stage (vulkan and sockets stuff)
  
  solved by puting the correct order in the libraries, like this:
  
  3rdparty/vulkan/libspirv-tools-opt.a 3rdparty/vulkan/libspirv-tools.a -lws2_32  -lpsapi 
  
  inside build.ninja's LINK_LIBRARIES (this isn't optimal and it should be fixed in the CMakefiles instead but i don't know how to do it)

**Comment by InoriRus** [comment]
What compiler and linker do you use?

**Comment by zecoxao** [comment]
Used chocolatey to install required dependencies
first installed winlibs (llvm clang + mingw-w64 + gcc seh x64)
then installed ninja
then installed cmake
then installed git
then installed make

i then cloned the project, cd to the _Build folder and selected cmake for Eclipse+MinGW with ninja build

**Comment by zecoxao** [comment]
Maybe the issue here is probably lack of proper build instructions, but i'm 100% sure the executable i compiled is proper.

**Comment by InoriRus** [comment]
Please, check now

**Comment by zecoxao** [comment]
almost perfect, only fails at linking stage, with error that the program is not compatible with this version of windows (i'm using windows 11)

**Comment by zecoxao** [comment]
the executable still builds though, but on the mingw make one it deletes it on failure

**Comment by zecoxao** [comment]
can now confirm it compiles and links fine, closing issue
