### ISSUE TITLE
Difference or commonality with gpcs4 ?

### ISSUE THREAD

**Issue by UntysiastRUS** [InoriRus/Kyty#27]
Hello, I find it difficult to express my thought in English without an interpreter, (because I am Russian), but I would like to ask,

1. are you referring to the GPCS4 code? 
2. Is it possible to integrate the GPCS4 code to speed up your software development?

3. Is it possible to integrate your project with spine ?

I apologize if my questions seem inappropriate to you.

I'm not a developer.
But I even made a github for the sake of my question.

Why did you name your project Kyty?
Is it related to "whales" (animals)?

or is it a reference to whales - "rich people" ?

**Comment by Graubek** [comment]
Close this issue and move to discussions.
