### ISSUE TITLE
failure to link 3rdparty/rijndael/librijndael.a (only in the clang specific builds)

### ISSUE THREAD

**Issue by zecoxao** [InoriRus/Kyty#3]
FAILED: 3rdparty/rijndael/librijndael.a
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E rm -f 3rdparty\rijndael\librijndael.a && C:\ProgramData\chocolatey\lib\winlibs\tools\mingw64\bin\llvm-ar.exe qc 3rdparty\rijndael\librijndael.a  @CMakeFiles\rijndael.rsp && C:\ProgramData\chocolatey\lib\winlibs\tools\mingw64\bin\llvm-ranlib.exe 3rdparty\rijndael\librijndael.a && cd ."
C:\ProgramData\chocolatey\lib\winlibs\tools\mingw64\bin\llvm-ar.exe: error: unable to open '3rdparty\rijndael\librijndael.a': No such file or directory
[97/494] Building CXX object 3rdparty/vulkan/CMakeFiles/spirv-tools_obj.dir/source/binary.cpp.obj
ninja: build stopped: subcommand failed.

this might be related to the build tools i have and not be an issue of the emulator per se. clang-cl from winlibs was used.

**Comment by InoriRus** [comment]
**llvm-ar.exe** from winlibs is broken. It can be replaced with **ar.exe** from mingw
The bug is fixed in recent versions of llvm. But winlibs is slightly outdated.

**Comment by zecoxao** [comment]
thank you for the response. works as intended. closing...
