### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by thx4ever** [InoriRus/Kyty#4]
I get those errors when try to link with Visual Studio 2019 or 2022

KytyScripts.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl Kyty::Emulator::EmulatorSubsystem::Init(class Kyty::Core::SubsystemsList *)" (?Init@EmulatorSubsystem@Emulator@Kyty@@UEAAXPEAVSubsystemsList@Core@3@@Z)
2>KytyScripts.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl Kyty::Emulator::EmulatorSubsystem::Destroy(class Kyty::Core::SubsystemsList *)" (?Destroy@EmulatorSubsystem@Emulator@Kyty@@UEAAXPEAVSubsystemsList@Core@3@@Z)
2>KytyScripts.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl Kyty::Emulator::EmulatorSubsystem::UnexpectedShutdown(class Kyty::Core::SubsystemsList *)" (?UnexpectedShutdown@EmulatorSubsystem@Emulator@Kyty@@UEAAXPEAVSubsystemsList@Core@3@@Z)

Regards

**Comment by InoriRus** [comment]
What compiler and linker do you use?
Open **CMakeCache.txt** in your build folder and check values **CMAKE_CXX_COMPILER** and **CMAKE_LINKER**
There should be **clang-cl.exe** and **lld-link.exe**

**Comment by gandalfthewhite19890404** [comment]
Any chances for CI (Appveyor or Github Actions), it gonna be easier to get compiled binaries?

**Comment by InoriRus** [comment]
Appveyor CI is now supported

**Comment by thx4ever** [comment]
OK i managed to compile with Visual Studio clang version 12, thanks. closing...
