### ISSUE TITLE
launcher fails opening with "This application failed to start because no Qt5 plugin could be initialized"

### ISSUE THREAD

**Issue by zecoxao** [InoriRus/Kyty#5]
builds and links just fine, fc_script launches just fine, but when you try to launch the launcher (together with the required dll dependencies) that message pops up.

Any idea what it could be?

**Comment by InoriRus** [comment]
Try to perform "ninja install" and run launcher from "_bin" folder. It should contain "platforms/qwindows.dll" within install folder

**Comment by zecoxao** [comment]
works. closing issue...
